### ISSUE TITLE
StartScanning

### ISSUE THREAD

**Issue by l33333on** [romain974/PyYDLidarX4#1]
Hi,
am I able to set the scanning frequency for the YDLidar X4 sensor somehow? When Im using the example reading code with the default chunk size of 6000 it takes ~500ms between each reading, -> 2Hz. Can I somehow set this up to like 10Hz?

**Comment by l33333on** [comment]
Solved it by using the official SDK: https://github.com/YDLIDAR/YDLidar-SDK

**Comment by romain974** [comment]
You have a parameter when creating the class:  chunk_size=6000
Romain,

**Comment by l33333on** [comment]
Somehow I still didnt achieve the 7Hz... Official SDK worked flawlessly
